# Generated by Django 4.2.5 on 2023-09-15 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('type', models.CharField(default='', max_length=200)),
                ('time_of_passing', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('desc', models.TextField(default='Samsung or Iphone ?')),
            ],
            options={
                'db_table': 'GameModel',
            },
        ),
    ]
