# Generated by Django 4.2.5 on 2023-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='desc',
            field=models.TextField(default='Do you like games?'),
        ),
    ]
